apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: sdu-evac-backend
  name: sdu-evac-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sdu-evac-backend
  template:
    metadata:
      labels:
        app: sdu-evac-backend
    spec:
      containers:
      - image: ghcr.io/jaco5157/sdu-evac-backend:{IMG_TAG}
        name: sdu-evac-backend
        ports:
        - containerPort: 80
