apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: sdu-evac-frontend
  name: sdu-evac-frontend
spec:
  replicas: 0
  selector:
    matchLabels:
      app: sdu-evac-frontend
  template:
    metadata:
      labels:
        app: sdu-evac-frontend
    spec:
      containers:
      - image: ghcr.io/jaco5157/sdu-evac-frontend:{IMG_TAG}
        name: sdu-evac-frontend
        ports:
        - containerPort: 80
